<Project>
    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    </PropertyGroup>

    <ItemGroup>
        <PackageVersion Include="Microsoft.Extensions.Hosting" Version="11.0.0-rc.1.26425.128" />
        <PackageVersion Include="Microsoft.Extensions.Http" Version="11.0.0-rc.1.26425.128" />
        <PackageVersion Include="NuGet.Versioning" Version="7.9.0" />
        <PackageVersion Include="Spectre.Console" Version="0.57.2" />
        <PackageVersion Include="System.CommandLine" Version="2.0.12" />
    </ItemGroup>
</Project>
