<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <ProjectReference Include="../../Discovery/DotnetManager.InstalledDotnet/DotnetManager.InstalledDotnet.csproj"/>
        <ProjectReference Include="../../Shared/DotnetManager.Core/DotnetManager.Core.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions"/>
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions"/>
        <PackageReference Include="NuGet.Versioning"/>
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="DotnetManager.UnitTests"/>
    </ItemGroup>
</Project>
