<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk"/>
        <PackageReference Include="xunit"/>
        <PackageReference Include="xunit.runner.visualstudio">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="coverlet.collector">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../../Application/DotnetManager/DotnetManager.csproj"/>
        <ProjectReference Include="../../Discovery/DotnetManager.InstalledDotnet/DotnetManager.InstalledDotnet.csproj"/>
        <ProjectReference Include="../../Discovery/DotnetManager.ReleaseMetadata/DotnetManager.ReleaseMetadata.csproj"/>
        <ProjectReference Include="../../Environment/DotnetManager.UserEnvironment/DotnetManager.UserEnvironment.csproj"/>
        <ProjectReference Include="../../Installation/DotnetManager.Installation/DotnetManager.Installation.csproj"/>
        <ProjectReference Include="../../Installation/DotnetManager.Installation.Resolver/DotnetManager.Installation.Resolver.csproj"/>
        <ProjectReference Include="../../Removal/DotnetManager.Removal/DotnetManager.Removal.csproj"/>
        <ProjectReference Include="../../Shared/DotnetManager.Core/DotnetManager.Core.csproj"/>
    </ItemGroup>
</Project>
