<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk"/>
        <PackageReference Include="xunit"/>
        <PackageReference Include="xunit.runner.visualstudio">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="coverlet.collector">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../../DotnetManager/DotnetManager.csproj"/>
        <ProjectReference Include="../../DotnetManager.Core/DotnetManager.Core.csproj"/>
        <ProjectReference Include="../../DotnetManager.Installation/DotnetManager.Installation.csproj"/>
        <ProjectReference Include="../../DotnetManager.InstalledDotnet/DotnetManager.InstalledDotnet.csproj"/>
        <ProjectReference Include="../../DotnetManager.ReleaseMetadata/DotnetManager.ReleaseMetadata.csproj"/>
        <ProjectReference Include="../../DotnetManager.Removal/DotnetManager.Removal.csproj"/>
    </ItemGroup>
</Project>
